name: PRINT THAT FLAG yes please
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CTF
    steps:
      - name: Print FLAG
        run: "echo $FLAG | base64"
        env:
          FLAG: ${{ secrets.FLAG }}