name: PRINT THAT FLAG
on:
  pull_request_target:
    branches:
      - test-workflow
jobs:
  build:
    runs-on: ubuntu-latest
    environment: CTF
    steps:
      - name: Print FLAG Test
        #run: "echo $FLAG | base64"
        run: "echo FLAG test"
        env:
          FLAG: ${{ secrets.FLAG }}